### ISSUE TITLE
Provide an easy option to change the pygments style

### ISSUE THREAD

**Issue by 3ter** [gregorrr/anki-auto-markdown#10]
Hi there,

there are a lot of styles in `~\AppData\Roaming\Anki2\addons21\1030875226\pygments\styles` and I don't know how to change from the `default` style to one of those.

I was only able to find out that you can remove the line numbers by commenting out the linese after `CSSFILE_TEMPLATE = '''\` in the file `~\AppData\Roaming\Anki2\addons21\1030875226\pygments\formatters\html.py`
```css
/* td.linenos { background-color: #f0f0f0; padding-right: 10px; }
span.lineno { background-color: #f0f0f0; padding: 0 5px 0 5px; } */
```

I'm closing this because I forgot to look into the Config in the Add-ons menu in Anki, where it was explained perfectly 😃
