### ISSUE TITLE
Code blocks are centered in study mode

### ISSUE THREAD

**Issue by vtpros** [gregorrr/anki-auto-markdown#23]
When I create a code block:

\```ruby
some code
\```
anki centers it during a study session: https://imgur.com/pkwFdVO
Can it be avoided?
The text on the back of the card:
[card.txt](https://github.com/gregorrr/anki-auto-markdown/files/5204376/card.txt)

**Comment by vtpros** [comment]
Fixed it by adding additional styling for `codehilite` class to the card type template:
```css
.card {
 font-family: arial;
 font-size: 20px;
 text-align: center;
 color: black;
 background-color: white;
}
.codehilite {
 text-align: left;
}
```
